### ISSUE TITLE
All Release Reference Documentation Links are not working anymore 

### ISSUE THREAD

**Issue by thePhil** [reactor/projectreactor.io#109]
All [Release Reference Documentation Links](https://projectreactor.io/docs/core/release/reference/) are not working anymore

## Expected Behavior

Open the Release version reference documentation

## Actual Behavior

Receipt of a general 404 error page.

## Steps to Reproduce

Open the Release Reference documentation 
--> [CLICK ME](https://projectreactor.io/docs/core/release/reference/) <--

## Possible Solution

Use the [Snapshot documentation](https://projectreactor.io/docs/core/snapshot/reference/) until fixed.

**Comment by violetagg** [comment]
@thePhil The documentation should be available again.
