### ISSUE TITLE
Release documentation is down

### ISSUE THREAD

**Issue by 34875634567** [reactor/projectreactor.io#112]
## Actual Behavior
Release documentation seems to be down: 

![image](https://user-images.githubusercontent.com/45098020/220175557-a8a62e5a-c6db-42cd-9f99-5129f06ff955.png)

Possibly a repeat of https://github.com/reactor/projectreactor.io/issues/109
## Steps to Reproduce
 Go to <https://projectreactor.io/docs/core/release/api/>

**Comment by violetagg** [comment]
@34875634567 The documentation should be available now.
