### ISSUE TITLE
Learn page suggestion: Access Forbidden to Documentation

### ISSUE THREAD

**Issue by mrgrew** [reactor/projectreactor.io#142]
# Resource Quick Description / Title

Access Forbidden

# Resource link

I'm getting a 403 Forbidden from https://projectreactor.io/docs/core/3.6.1/reference/index.html

# Why you feel this would be a great addition

I want to look at the documentation version that Spring Boot uses.

**Comment by pderop** [comment]
@mrgrew ,

We are working on the problem, see https://github.com/reactor/projectreactor.io/issues/143
