### ISSUE TITLE
Broken links to github in Reference Manual http://projectreactor.io/docs/reference

### ISSUE THREAD

**Issue by DKorchuganov** [reactor/projectreactor.io#2]
There are a lot of broken links to github in the Reference Manual, for example:
https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/fn/Consumer.java
https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/fn/BiConsumer.java
and so on...

**Comment by smaldini** [comment]
Yes we just transitioned the repos (https://github.com/reactor/reactor/issues/600), bear with us the time we provide the necessary updates to the site (btw snapshot site is http://next.projectreactor.io).

**Comment by smaldini** [comment]
Leaving issue open until we solve it tho.

**Comment by simonbasle** [comment]
The reference guide is being rewritten in reactor-core (see reactor/reactor-core#404), closing this as this is no longer the relevant issue
