### ISSUE TITLE
Resolve reference guide through `reactor-core-VERSION-docs.zip` now

### ISSUE THREAD

**Issue by lhotari** [reactor/projectreactor.io#48]
I went to https://projectreactor.io/docs and clicked on the Reactor Core Reference -> Release link which points to https://projectreactor.io/docs/core/release/reference/. 
This link returns a 404 at the moment.

**Comment by songjhh** [comment]
me too

**Comment by simonbasle** [comment]
yes, the latest release broke the naming of the zip file(s) that contains the reference guides :(

**Comment by simonbasle** [comment]
it is not a matter of renaming the zips in the build, but rather the new mode of publication that enforces following Maven naming conventions, which the previous publication didn't. as a result the site tries to resolve a zip file that doesn't appear to exist, because it is named differently.

**Comment by simonbasle** [comment]
The old convention is now invalid for the following version ranges:
 - `core` Californium: from `3.2.13.RELEASE` (included) to `3.3.0.BUILD-SNAPSHOT` (NOT included)
 - `core` Dysprosium: from `3.3.1.RELEASE` (included) onwards
 - `netty` Californium: from `0.8.10.RELEASE` (included) to `0.9.0.BUILD-SNAPSHOT` (NOT included)
 - `netty` Dysprosium: from `0.9.2.RELEASE` (included) onwards
