### ISSUE TITLE
A typo in the Reference Guide

### ISSUE THREAD

**Issue by skozlov** [reactor/projectreactor.io#52]
[Here](https://projectreactor.io/docs/core/release/reference/#context):
> As an illustration of what it looks like, the following example both **writes** from and writes to Context:

It should be `reads from`, doesn't it?

**Comment by simonbasle** [comment]
Sorry this fell through the cracks, the site's repo is far less monitored than the `reactor-core` one (in which the reference guide lives). This has been fixed in the meantime.
