### ISSUE TITLE
Getting error 405 method not allowed on client calls using Webclient

### ISSUE THREAD

**Issue by rohan-new** [reactor/projectreactor.io#73]
I am making multiple client calls to other Microservices from the Weblux app using Weblcient. There are over 500 elements in a flux and each element makes several api calls(each publisher makes 10 client calls) to other microservices. For some reason , which I dont know, for some requests , I am getting the  error **405 method not allowed**, even though the request never changes for every item in the publisher. 

## Expected Behavior
It should never give request not allowed error.

``` private Mono<Map> performGetRequest(String URI) {
        Mono<Map> responseMono = this.webClientBuilder.baseUrl(URI).build()
                .get()
                .retrieve()
                .bodyToMono(Map.class)
                .log()
                .retryWhen(Retry.fixedDelay(1, Duration.ofMillis(200)));
        return responseMono ;
    }
```
This is the method used by all the items inside the Flux to make a client call. I have tried shifting weblcient calls to different scheduler , so that they dont share the same thread pool as of the application server, but this hack didnt solve the issue.

**Comment by simonbasle** [comment]
This issue doesn't belong in `projectreactor.io` repository which hosts the Reactor website.
I don't think it has anything to do with Reactor in particular, and the best place is probably to ask a question on [StackOverflow](https://stackoverflow.com/tags/spring-webflux)
