### ISSUE TITLE
javadoc URLs broken at https://projectreactor.io/docs/core/release/api/

### ISSUE THREAD

**Issue by osi** [reactor/projectreactor.io#96]
## Expected Behavior

https://projectreactor.io/docs/core/release/api/ links to the current javadocs

## Actual Behavior

404

## Steps to Reproduce

1. go to https://projectreactor.io/docs
2. follow link to release javadocs, which goes to https://projectreactor.io/docs/core/release/api/
3. get 404 page which says to open an issue

**Comment by joshuapetryk** [comment]
+1.. very unfortunate timing

**Comment by violetagg** [comment]
We are aware that http://repo.spring.io is currently unavailable, because of that the documentation is also not available.
https://twitter.com/springops/status/1544719860340428800

**Comment by violetagg** [comment]
The documentation should be available.
