### ISSUE TITLE
Docs are returing a 404 https://projectreactor.io/docs/core/release/reference/

### ISSUE THREAD

**Issue by jorge-pineda-discovery** [reactor/projectreactor.io#97]
When I access the url above which I used to be able to access, it returns a 404

## Expected Behavior

A doc should be displayed on Project reactor core
## Actual Behavior

I get a 404
## Steps to Reproduce

https://projectreactor.io/docs/core/release/reference/#context
```java
@Test
public void repoCase() {

}
```

## Possible Solution

If a new url contains this info, redirect https://projectreactor.io/docs/core/release/reference/#context to that new url

**Comment by violetagg** [comment]
@jorge-pineda-discovery This is duplicate to #96
