### ISSUE TITLE
Documentation doesn't work on https://projectreactor.io/

### ISSUE THREAD

**Issue by ig0revich** [reactor/projectreactor.io#99]
Hello,

I was passing https://tech.io/playgrounds/929/reactive-programming-with-reactor-3 workshop and found that all documentation on projectreactor.io got broken. For example https://projectreactor.io/docs/core/release/reference/ shows 

![image](https://user-images.githubusercontent.com/13301903/179410929-42e7e65d-2f5d-4e65-924d-f695027ac609.png)

Please take a look.

**Comment by violetagg** [comment]
It should be accessible again
